### ISSUE TITLE
CKAN Data not appearing in Wordpress

### ISSUE THREAD

**Issue by Wheresitat** [open-data-toronto/docker-local-environment#13] opened 2019-10-07 21:38 UTC
Hello,

I ran the quick start script without issue, it was great, it downloaded, updated and installed the necessary scripts, modules and containers.
I'm able to access the containers and they start fine, i ran the command to add the dummy data into CKAN which also worked fine.
I followed the instructions to modify Wordpress settings to use the templates required, also no issue here.

I'm trying to view the dummy data now from Wordpress, i can't see anything. It's just a blank catalog page.
http://prntscr.com/pg6bs7

Any ideas?

**Comment by dottyz** [comment] 2019-10-07 21:46
If you open the web console, what are the errors?

**Comment by Wheresitat** [comment] 2019-10-07 22:05
> If you open the web console, what are the errors?

Don't get any errors, looks fine:
Wordpress is just missing any data in the catalog.
http://prntscr.com/pg6l85

**Comment by dottyz** [comment] 2019-10-08 13:29
No errors in both CKAN and WP web console on the catalogue pages? 

I think this would most likely be an WP theme issue since CKAN seem to have all the content. You can validate this using the package_search CKAN API endpoint with an empty query parameter and see if the expected results are returned. 

Which version of the WP theme are you using?

**Comment by Wheresitat** [comment] 2019-10-08 20:26
No, can't see any errors on CKAN or Wordpress.
I'm unsure of the theme version, just says blank:
http://prntscr.com/pgmtsk

The API call appears to work.
![image](https://user-images.githubusercontent.com/14259134/66430560-14521c00-ea66-11e9-8e01-94aad48f5cf7.png)


To confuse things a little more, when i load the catalog page i get this screen which quickly disappears, getting a screenshot was tricky.
http://prntscr.com/pgnvs7

**Comment by dottyz** [comment] 2019-10-09 13:48
That is strange. Since there are no errors, its hard to know exactly what the issue is. You could try a few different things from here on: 

1. Run `git describe --tags` in both the CKAN and WP directories and make sure the tag versions are v2.1.3 for CKAN and v2.1.3.1 for WP

2. Another thing that may be causing the issue is CORS, you could try to install an extension that allows CORS (eg. https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en) and see if that helps. 

3. Try visiting `<your CKAN URL>/api/3/action/catalogue_search?type=full&rows=10&sort=last_refreshed+desc&start=0` and see if that returns you a list of packages

**Comment by Wheresitat** [comment] 2019-10-09 20:39
1. Thanks for your help, i only cloned this one docker-local-environment repo, so I've got this:
/wp-open-data-toronto$ git describe --tags
v2.1-qa.1
docker-local-environment$ git describe --tags
v2.1.3
/stack/ckan# git describe --tags
demo-0.2-12182-g42596a014

2. Added CORS and it didn't seem to help

3. This worked fine, https://pastebin.com/CBdYC6tE

The wordpress version is out of date, i'll try re running the quick setup script but updating wordpress to latest and let you know how it goes.

**Comment by dottyz** [comment] 2019-10-10 14:03
Sounds good. Instead of changing the quick start script, you can also just go into the directory where the WP code is and run `git checkout v2.1.3.1`

**Comment by Wheresitat** [comment] 2019-10-10 22:22
Unfortunately i have the same issue with the latest version of Wordpress, nothing appears on the wordpress site. Any other ideas??

**Comment by dottyz** [comment] 2019-10-14 13:53
You have to be on exactly v2.1.3.1, latest version of WP code would require also an corresponding CKAN update.

**Comment by Wheresitat** [comment] 2019-10-14 21:31
Have tried executing this on a brand new server, fresh ubuntu 19.04 install, ran the quick start script and configured as documented. Same issue, nothing appears in Wordpress, old version or latest. :(

**Comment by dottyz** [comment] 2019-10-15 14:45
I just ran the quickstart script from a new computer (Mac OS) and followed the steps. Everything seems to be OK for me using Chrome so I'm pretty stumped about why this is not working for you. Could also be a browser issue?

**Comment by dottyz** [comment] 2019-10-21 14:56
Closing the issue after discussions via email. Caused by change in configuration of how CKAN and WP are connected.

**Closed as completed by dottyz** 2019-10-21 14:56 UTC
